### PR TITLE
Automatically retry conda calls on CondaHTTPError

### LINKED ISSUE #325: Spurious test failures due to CondaHTTPError
**Problem description**

Sometimes, tests fail due to a `CondaHTTPError` that is thrown, e.g., during a `conda install`:
```
Solving environment: failed
CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json>
Elapsed: 00:10.026206
CF-RAY: 45a337c93dff9fb4-IAD
A remote server error occurred when trying to retrieve this URL.
A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```
See for example [here](https://travis-ci.org/astropy/ci-helpers/jobs/428621381#L964).
It sometimes becomes tedious to inspect and restart builds that fail due to that error (which is completely unrelated to the actual tests).

**Expected behavior**

The `ci-helpers` scripts should catch `CondaHTTPError`s and automatically retry the failed command.

### PR DESCRIPTION
**Pull request by zemanj**
Fixes #325

**Changes**

- Travis:
  - Added the environment variables `RETRY_ERRORS` (errors to search for), `RETRY_MAX` (maximum number of retries), and `RETRY_DELAY` (number of seconds to wait before retrying)
- AppVeyor:
  - The corresponding variables are `$env:RETRY_ERRORS`, `$env:RETRY_MAX`, and `$env:RETRY_DELAY`
- Travis and Appveyor:
  - If not set from outside of the corresponding scripts, the new variables are initialized as
    - `RETRY_ERRORS="CondaHTTPError"`
    - `RETRY_MAX=3`
    - `RETRY_DELAY=2`
  - All calls to `conda install` or `conda create` (and the like) are now wrapped by a function `retry_on_known_error()` that handles automatic re-execution of the wrapped commands if they fail due to any of the errors in `RETRY_ERRORS`. The function `retry_on_known_error()` does *not* interfere with the rest of the script execution.

### CODE REVIEW

**Comment by zemanj** [comment]
@bsipocz Sure, I'll do that once I fixed the appveyor script :wink:

**Comment by zemanj** [comment]
Hope this works now. :crossed_fingers:
If it does, I'll add the README docs.

**Comment by zemanj** [comment]
@bsipocz I think this should be ready for review

**Comment by bsipocz** [comment]
All looks very sensible to me. Thank you @zemanj for this enhancement!

**Pull request merged**
