### PR TITLE
Set up Windows SDK when calling pip install

### PR DESCRIPTION
**Pull request by embray**
pip installs should be preceded by the `%CMD_IN_ENV%` invokation to set up the Windows SDK environment when appropriate, since pip install will often (not always, depending on wheel availability) result in a build from source, in which case we presumably want to build for the same platform as the package that we're testing.

### CODE REVIEW

**Comment by bsipocz** [comment]
@embray - This needs a rebase and then we can merge it.

 (btw is it possible for a maintainer to rebase a PR somehow and push it back to the same PR?)

**Comment by embray** [comment]
@bsipocz I just clicked the (new?) "update branch" button to merge it into the latest master, so it shouldn't need to be rebased now.

**Comment by bsipocz** [comment]
Yes, you did it while I was writing the comment :)

**Comment by embray** [comment]
Cool--FWIW I was just now able to confirm locally that this resolved the issue.  Invoking pip through the windows_sdk.cmd script successfully set up the environment for using the Windows SDK (of which I also needed to install the correct version), and built astropy dev with all the right flags.

**Pull request merged**
