### PR TITLE
Undo pytest<6 pin

### PR DESCRIPTION
**Pull request by pllim**
Undo #453 because `pytest-doctestplus` 0.8.0 is out on PyPI.

### CODE REVIEW

**Comment by pllim** [comment]
Appveyor failures are unrelated.

**Comment by pllim** [comment]
astropy/astropy#10620 using pytest 6.0.1 and pytest-doctestplus 0.8.0 looks promising. There are some warnings but they don't turn into failures.

```
=============================== warnings summary ===============================
/home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148
  /home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: asdf_schema_root
  
    self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
/home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148
  /home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: asdf_schema_tests_enabled
  
    self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
/home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148
  /home/travis/build/astropy/astropy/.tox/py37-test/lib/python3.7/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: qt_no_exception_capture
  
    self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=== 13461 passed, 1027 skipped, 104 xfailed, 3 warnings in 257.86s (0:04:17) ===
```

**Comment by pllim** [comment]
p.s. As far as I can dig into `pytest` code, there is no simple way to turn off those warnings. I tried ignoring them in `setup.cfg` but that didn't work. We can either just live with it or ask @niccodemus

**Comment by nicoddemus** [comment]
Hey!

Hmm those warnings mean that those options are not not registered and are being ignored. `asdf_schema_root` and `asdf_schema_tests_enabled` I don't recognize, but `qt_no_exception_capture` is from `pytest-qt` and should not be appearing if `pytest-qt` is installed.

Can I see the pytest header from that run? (I did take a quick look at the AppVeyor build but couldn't find it)

I think those filters can be ignored by using the `filterwarnings` option, but because they are configuration warnings that might not work (the reason is complicated, but mainly because the warnings plugin might not have registered at that point yet to capture/filter out the warning).

**Comment by bsipocz** [comment]
@nicoddemus - ignore appveyor, we're ditching it, it's failing with unrelated stuff.

**Comment by pllim** [comment]
Hello, @nicoddemus ! Thanks for the reply. Yes, those are set in https://github.com/astropy/astropy/blob/ab3577da3377e9c488a294755e641496be57f235/setup.cfg#L92 (starting from that line) and the example log is at https://travis-ci.org/github/astropy/astropy/jobs/713837307 

* The `asdf` stuff is optional, so it is not always installed for all the jobs.
* We don't do `qt` but we added it because someone complained that the test broke without the setting when they have `pytest-qt` installed.

**Comment by nicoddemus** [comment]
I see, thanks @bsipocz and @pllim.

@pllim can you please add this line to your `filterwarnings` list

```
  ignore:Unknown config ini key
```

But as I said, that might not work (we really should look into fixing that).

**Comment by pllim** [comment]
Re: https://github.com/astropy/ci-helpers/pull/455#issuecomment-667435324 -- Did not work. Same warnings still show.

**Comment by nicoddemus** [comment]
Yeah unfortunately as I suspected, the cause is due to https://github.com/pytest-dev/pytest/issues/6681. Not much that can be done at this time, I'm afraid. 😕

**Comment by pllim** [comment]
Thank you very much for your help, @nicoddemus ! I've added a comment to that pytest issue.

**Comment by pllim** [comment]
For `ci-helpers` maintainers, please merge this.

**Comment by nicoddemus** [comment]
Hey folks,

FTR, https://github.com/pytest-dev/pytest/pull/7649 should make that warning possible to filter out. 👍

**Pull request merged**
