### PR TITLE
Pin pytest to latest compatible versions if version not specified

### PR DESCRIPTION
**Pull request by astrofrog**
WIP - I'm going to try this out with reproject

Note that this might not be needed if we can get https://github.com/conda-forge/astropy-feedstock/pull/43 and https://github.com/conda-forge/astropy-feedstock/pull/44 merged in and propagate to the channels used here.

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - I've merged the conda-forge PRs, and also #349, so this will need a rebase, and probably a retest, too to see whether we need it in or not.

**Comment by bsipocz** [comment]
(But actually I think we'll need it as hardly anyone uses astropy from conda-forge, so unless you also trigger the anaconda folks to rebuild we need to pin the pytest version here).

**Comment by astrofrog** [comment]
I'm re-running the reproject tests (which were failing) here: https://travis-ci.org/astrofrog/reproject/builds/428950600

**Comment by astrofrog** [comment]
astropy LTS builds haven't been copied over to the astropy channel yet: https://github.com/astropy/conda-channel-astropy/issues/127#issuecomment-442361539

**Comment by astrofrog** [comment]
Ah right most packages will be using defaults, I thought they would be using the astropy channel (like reproject does) but I think that might be a special case.

**Comment by bsipocz** [comment]
I suppose at the end we'll need this, e.g. this very recent astroplan 2.7 tests picked up pytest 4....

**Comment by astrofrog** [comment]
The conda packages in defaults now specify the pytest restriction. Once this is also fixed in the astropy channel, I think we should be ok?

**Comment by bsipocz** [comment]
I think we don't need this any more. 
@astrofrog - are you happy to close it?

**Pull request closed without merging**
