### PR TITLE
Limit even more coverage 

### PR DESCRIPTION
**Pull request by bsipocz**
Maybe the third time will be the winning one.

### CODE REVIEW

**Comment by djhoese** [comment]
I'm seeing some odd behavior in some of my builds that are having trouble finding dependencies because of these changes. Is there an issue explaining this? Why is this in ci-helpers and not in the astropy dependency list?

**Comment by bsipocz** [comment]
Because it affects all of the astropy downstream packages that use the astropy test runner. That's tens if not hundreds of repos. This situation was exactly the motivation behind ci-helpers, but I'm happy have any workarounds that would work for everyone.

**Comment by bsipocz** [comment]
e.g. hacky, but we could deal with having a `COVERAGE_VERSION` or similar

**Comment by djhoese** [comment]
My understanding from the changes is that if I specify `pytest-cov coverage` in my dependencies it should get around this forced version, right?

You're right, this is astropy's project and thank you all for making it available. Is there an issue that I can see that describes why coverage>=5 breaks things in the test runner? I'm curious if I can help or if it is something I should avoid in my own projects.

**Pull request merged**
