### PR TITLE
Fix appveyor builds with new conda

### PR DESCRIPTION
**Pull request by djhoese**
Successor to #403

### CODE REVIEW

**Comment by djhoese** [comment]
@bsipocz @mwcraig One of the test failures for this is because python 3.4 is no longer available. Should I update it to 3.6/3.7 or something else?

```
        # For the Numpy dev build, we also specify a conda package that depends
        # on Numpy to make sure that Numpy dev is used (because conda will also
        # install Numpy stable)

      - PYTHON_VERSION: "3.4"
        NUMPY_VERSION: "1.9"
```

**Comment by djhoese** [comment]
Oh and another test is failing because astropy no longer supports python 3.5.

**Comment by bsipocz** [comment]
Isn't the case that it's available on another channel, etc?

However, given that 3.4 reached its official end-of-life (https://www.python.org/dev/peps/pep-0429/#id4), I'm OK if we remove support of it here, too.

@astrofrog - are you on board with that?

**Comment by djhoese** [comment]
@mwcraig In your PR, is there a reason you avoided doing `conda init powershell`?

**Comment by astrofrog** [comment]
Dropping 3.4 is definitely fine!

**Comment by djhoese** [comment]
@astrofrog I'll move the necessary python versions to 3.7 unless someone has a preference for an exact version? I'd prefer 3.7 to give ci-helpers some time before things start breaking again.

I'm testing some stuff right now, but will likely revert back to the last working state before I change the python versions.

**Comment by djhoese** [comment]
Now that I upgraded the following environment, it is failing because numpy 1.13 doesn't support python 3.7 (at least it isn't available from the used channels):

```
      - PYTHON_VERSION: "3.7"
        NUMPY_VERSION: "1.13"
        ASTROPY_VERSION: "lts"
```

Either use python 3.6 or upgrade to a newer numpy?

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
  - numpy=1.13 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
```

**Comment by bsipocz** [comment]
@djhoese @mwcraig - Should I merge this or #416 or both?

**Comment by bsipocz** [comment]
Rebased to get rid of the master merge, as well as the complaint that this is not up-to-date.

**Comment by bsipocz** [comment]
Oh, never mind this is the one overridden by #416.

**Comment by bsipocz** [comment]
(not sure how/why the commit also showed up here)

**Comment by bsipocz** [comment]
no worries, I'm still  super confused what magic you two did here :)

**Pull request closed without merging**
