### PR TITLE
sunpy stable is now 0.8.4

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by bsipocz** [comment]
@Cadair - you need to update the test file, too. Also, feel free to remove this manual version setting and let conda decide what to pick up, I don't have any strong option that we need to keep this pinning for sunpy (unlike for numpy and astropy, given that we run into issues with those multiple times)

**Comment by Cadair** [comment]
I can see the logic for keeping the pinning. We shall add this to our post-release todo list.

**Comment by bsipocz** [comment]
Thanks @Cadair!

**Comment by bsipocz** [comment]
ahh, this missed appveyor, but I'll fix that in another PR.

**Pull request merged**
