### PR TITLE
MNT: Replace master with main

### PR DESCRIPTION
**Pull request by pllim**
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.

This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

This is part of #469

### CODE REVIEW

**Comment by pllim** [comment]
Does depend on APE repo renaming too.

**Comment by bsipocz** [comment]
I would say this is a good place to start to break the almost circular dependencies, so 👍 on merging now.

**Comment by pllim** [comment]
Hmm... If the renaming also does auto-redirect, then maybe we should have just renamed it instead of making a copy. But I guess that ship has sailed for this repo.

https://github.com/astropy/astropy-APEs/issues/66#issuecomment-795833630

**Comment by bsipocz** [comment]
Yep, same mistake I made for astroml, but I suppose it's better to be safe than sorry (and we can still delete the copy once you get an answer for the helpdesk ticket)

**Comment by pllim** [comment]
From https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/ , it says, "This change only affects view links; other types of links (like edit links and blame links) don't redirect."

Do you think we can just go ahead and do #471 now and see what happens?

**Pull request merged**
