### PR TITLE
Updating conda to the 4.4.x branch

### PR DESCRIPTION
**Pull request by bsipocz**
This is very experimental and probably a premature upgrade, so needs to be tested with multiple packages.

@dan - could you take this branch for a spin for your packages?

https://travis-ci.org/bsipocz/astropy/builds/342440186
https://travis-ci.org/bsipocz/photutils/builds/342441641

### CODE REVIEW

**Comment by drdavella** [comment]
@bsipocz see linked issues for tests that are running.

**Comment by bsipocz** [comment]
@drdavella - Thanks. The syntax I usually use is `git clone -b conda_pin_4410 git://github.com/bsipocz/ci-helpers.git`

**Comment by drdavella** [comment]
Should this be closed?

**Comment by bsipocz** [comment]
This is superseded by #308

**Pull request closed without merging**
