### PR TITLE
Export PYTHON_VERSION

### LINKED ISSUE #282: KeyError: 'PYTHON_VERSION' on Travis CI
xref spacetelescope/stginga#154

Log: https://travis-ci.org/spacetelescope/stginga/jobs/345804779

### PR DESCRIPTION
**Pull request by pllim**
Fix #282 (specifically just the `KeyError`, not the rest of the failure in `stginga`)

### CODE REVIEW

**Comment by bsipocz** [comment]
This will now need a rebase. Also ideally a test job in the travis matrix with the language set to python and check whether `PYTHON_VERSION` indeed exists. I can do these if needed but not on this week.

**Comment by pllim** [comment]
@bsipocz , just forcing "export" fixed my problem (which did not cause the actual failure anyway), so I am not convinced that extra logic is necessary here. But feel free to do what you need to do. Thanks!

**Comment by bsipocz** [comment]
Others have run into this issue, too so it's very much time to get it merged.

I've rebased and added a bit more explanatory commit message. The PYTHON_VERSION was properly inherited from the travis matrix, but it needs to be exported to become visible to the python subprocess.

**Comment by pllim** [comment]
Thanks!

**Comment by bsipocz** [comment]
thanks @pllim!

**Pull request merged**
