### PR TITLE
Limit pytest version to <3.2.0

### PR DESCRIPTION
**Pull request by bsipocz**
Remove this limitation once https://github.com/astropy/astropy/pull/6419 is fully understood and solved.

cc @astrofrog

### CODE REVIEW

**Comment by bsipocz** [comment]
not sure what goes wrong for appveyor, @astrofrog can you spot a typo?

**Comment by bsipocz** [comment]
I'm really out of ideas here, powershell just hates me. @astrofrog @MSeifert04 any ideas how could this be done for appveyor?

**Comment by MSeifert04** [comment]
I'm not sure what you want but `Write-Host` doesn't return anything (just prints to console). Also `OutFile` clobbers the whole file.

If you just want to create a new file that contains `pytest <3.2` (+newline) just use

```
"pytest <3.2" | Out-File test.dat
```

**Comment by bsipocz** [comment]
@MSeifert04 - Thanks. My last commit was a bit misleading, I kept amending my trials, I've started off without the pin file to have the limitation in the conda install line, then tried all sorts of quoting, echo, etc, then remembered that powershell is a beast and has a few specific command...

**Comment by MSeifert04** [comment]
as long as it works 👍  :)

**Comment by bsipocz** [comment]
yes, it's a shame to do it this way but I'm not willing to properly dig into and learn the mess of powershell 😉

**Comment by bsipocz** [comment]
Hmm, it didn't work and now I'm back at the same pit I was yesterday with those weird characters

https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.757/job/reutxgf6nx7e7wji#L267

**Comment by MSeifert04** [comment]
Ah, that's just some encoding issue, you could use `"pytest <3.2" | Out-File ... -Encoding ASCII`

**Comment by bsipocz** [comment]
At the end I used the super ugly hack of copying over a canned version of that file from here. There are no words to describe how much I dislike powershell.

**Pull request merged**
