### PR TITLE
Implement DEBUG environment variable for AppVeyor

### PR DESCRIPTION
**Pull request by astrofrog**
We need to check if it works by looking at the log of the build that uses it.

### CODE REVIEW

**Comment by bsipocz** [comment]
This is a long overdue idea, thanks for digging down for the solution.

**Comment by bsipocz** [comment]
Also looking at the output there is more there than usual. However I wonder whether printing out all of the env variables would be useful as well when ``DEBUG`` is opted in. (I'm not sure how to do it, but you did that with one of your past experimental commits (that was removed after rebases)).

**Comment by astrofrog** [comment]
@bsipocz - I'm not sure how to do it either! 😆

**Comment by bsipocz** [comment]
@astrofrog - Maybe then just add a ``python -c "import os; print(os.environ)"`` line as debug for the env variables?
Either way please rebase this, so then we can merge it.

**Comment by astrofrog** [comment]
@bsipocz - i think the last commit should do the trick. I enabled DEBUG for the simple 2.7 build. This should show the commands run and the environment variables.

**Comment by bsipocz** [comment]
@astrofrog - Thanks!

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Pull request merged**
