### PR TITLE
Adding [docs only] and [build docs] custom tags

### LINKED ISSUE #188: Create custom skip tags
e.g ``[skip travis]`` or ``[docs only]``, etc.

related issue astropy/astropy#3933

### PR DESCRIPTION
**Pull request by bsipocz**
Minor clean up of [travis skip], and addition of two new custom tags to the top level script.

This address all ideas in and thus close #188

### CODE REVIEW

**Comment by bsipocz** [comment]
@Cadair @astrofrog - I fear this is something that cannot really be tested within this repo, if you up to it, please give it a go.  (E.g. without usage I've totally forgot within a month that `[skip travis]` is already a thing...)

**Comment by bsipocz** [comment]
I'll send out an e-mail to astropy-dev and the maintainers list about this, but also tagging a few people who I know are keen to keep the CI footprint minimal (though it would be great to educate the less keen people about the merits of it). @mhvk @hamogu @cdeil @eteq @astrofrog @pllim @larrybradley @Cadair

All the new custom tags work like the prerelease builds, and set the commit status to pass. Obviously it *doesn't* mean that the tests are passing. We can assume that the author has good reasons for the skip, but maintainers should be aware of this, too to avoid after merge surprises.

So, now we have ``[skip travis]`` and ``[travis skip]`` to skip travis. And more importantly have ``[docs only]`` or ``[build docs]`` that will skip all jobs except the docs building ones. 

These tags cannot be tested in this repo, but I run a few tests on a fork of mine. While it works as expected, please look out for issues that are related to this.

**Comment by mhvk** [comment]
Fantastic! We should be sure to document it also in the development guide.

**Comment by pllim** [comment]
That's a great addition. Thanks, @bsipocz !

**Comment by mwcraig** [comment]
This is excellent !!

**Comment by larrybradley** [comment]
This is great.  Thanks, @bsipocz!

**Comment by kain88-de** [comment]
@bsipocz I'm not sure but this might have broken the cron job for MDAnalysis. For us it is now always run. Even during a normal PR. Below is an example job with `DEBUG=True`

[Cron Job](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/243968646)
[Whole Travis Build](https://travis-ci.org/MDAnalysis/mdanalysis/builds/243968634?utm_source=github_status&utm_medium=notification)

**Comment by bsipocz** [comment]
@kain88-de - Indeed, this PR cleans up a bit of the logic of doing all the build checking for the need of cancelling builds before any install happens. I suggest to use common ``setup_conda.py`` (as shown in the README) rather than the OS specific setup files.

**Comment by kain88-de** [comment]
Ah yeah thank you. I overlooked that we use the specific init script.

**Pull request merged**
