### PR TITLE
Install pyerfa for astropy dev

### PR DESCRIPTION
**Pull request by pllim**
To get around CI downstream failing because there is no pyerfa for astropy dev. Also see astropy/astropy#10329

### CODE REVIEW

**Comment by pllim** [comment]
I don't think the failures are related.

**Comment by pllim** [comment]
(And I cannot merge this myself.)

**Comment by bsipocz** [comment]
I don't have time to investigate the first failure with pytest-dev version. The second one is trivial, bump the python version or limit mpl in travis for that job.
As for appveryor, for the first failure I would just remove sunpy dev altogether. Given sunpy is not using ci-helpers any more, we could probably nuke it altogether, but that's beyond the scope.

But then the second failure for appveyor is related again.

**Comment by pllim** [comment]
My Appveyor-fu isn't strong. How do you tell it to pip install pyerfa instead of trying to look in conda? Although, shouldn't pyerfa be available on conda via Windows, @mhvk?

**Comment by mhvk** [comment]
I recall discussing that it should go on conda, and that it had been pre-approved, but am not sure how to actually get it there!

**Comment by bsipocz** [comment]
When many months ago I talked to the conda people about it they said they are happy to ship it. But, it first needs a feedstock on conda-forge, so I ping @mwcraig about it.

**Comment by bsipocz** [comment]
please do rebase

**Comment by pllim** [comment]
Hmm, looks like it's on conda-forge already? Then it is a mystery why conda was complaining about not finding it... https://github.com/conda-forge/pyerfa-feedstock

**Comment by pllim** [comment]
Tests passed with pip install.

**Comment by mwcraig** [comment]
> Hmm, looks like it's on conda-forge already? Then it is a mystery why conda was complaining about not finding it... https://github.com/conda-forge/pyerfa-feedstock

That is odd. I checked, and it is on both conda-forge and the astropy conda channel.

**Comment by pllim** [comment]
@mwcraig , the log is at https://ci.appveyor.com/project/Astropy/ci-helpers/builds/34011187/job/ddwr46a5l1vu5ytq

```
PackagesNotFoundError: The following packages are not available from current channels:
  - pyerfa
Current channels:
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
```

**Comment by pllim** [comment]
Ooooo maybe ci-helpers CI is not looking in conda-forge...

But then again, people installing `astropy` from the default conda channel should not be expected to look for `pyerfa` from non-default, right?

**Comment by bsipocz** [comment]
> But then again, people installing astropy from the default conda channel should not be expected to look for pyerfa from non-default, right?

yes. It's deliberate to not use conda-forge here. And it will end up in default when astropy requires it. And in the meantime we can install it from the astropy channel that is a curated subset of conda-forge.

**Comment by bsipocz** [comment]
All green, so let's merge.

**Pull request merged**
