### PR TITLE
Use --force when uninstalling astropy

### PR DESCRIPTION
**Pull request by astrofrog**
Otherwise we run into issues like this:

https://travis-ci.org/astropy/regions/jobs/174034243

cc @bsipocz

### CODE REVIEW

**Comment by bsipocz** [comment]
Looks reasonable to me.

Btw we're seeing similar issues with astroquery, e.g. https://travis-ci.org/bsipocz/astroquery/jobs/174230608 except that it wants for some reason uninstall aplpy. I guess building a new version for python 3.5.2 will be a good workaround, but it won't get rid of the underlying problem. 
If you have any idea for the solution, let me know.

**Comment by astrofrog** [comment]
Isn't that just because APLpy depends on Astropy too, so it tries to uninstall all dependents? This might fix it?

**Comment by bsipocz** [comment]
Oh, you're right. Apparently I looked but didn't see, focused so much on the last line.

**Comment by bsipocz** [comment]
However this failure also means that the latest astropy is not picked up from ``astropy-ci-extras`` for some reason.

**Comment by bsipocz** [comment]
@astrofrog - For some reason this PR didn't trigger an appveyor build (it's not even in the queue). Would you mind force pushing it to try to trigger? (Obviously that would make travis rerun again, but I haven't got a better idea)

**Comment by astrofrog** [comment]
Weird - seems to be ok now though (I've pushed again)

**Comment by astrofrog** [comment]
🕙

**Pull request merged**
