### PR TITLE
MNT: Use C99 to compile numpy-dev

### PR DESCRIPTION
**Pull request by pllim**
As suggested by @rgommers (thank you! 🙏 ) over at https://github.com/numpy/numpy/pull/12610#issuecomment-451721733 

I will open an experimental PR over as Astropy to use this branch and see what happens. 🤞 

Fix astropy/astropy#8318

### CODE REVIEW

**Comment by pllim** [comment]
Unfortunately, this does not seem to work. Example log: https://travis-ci.org/astropy/astropy/jobs/475919446 (and also the CI for this PR has the same error)

`option -s not recognized`

**Comment by rgommers** [comment]
Try `export CFLAGS="-std=c99"`, if that also doesn't work then I need some sleep first:)

**Comment by pllim** [comment]
Yay, tests passed! (Appveyor failure is unrelated.)

**Comment by pllim** [comment]
I guess we can still nitpick on whether we want that CFLAGS defined for all Numpy selections, but at least the solution is at hand now.

**Comment by bsipocz** [comment]
Thanks @pllim and @rgommers!

**Pull request merged**
