### PR TITLE
Remove astropy-ci-extras from the default conda channels

### PR DESCRIPTION
**Pull request by bsipocz**
This is a workaround for currently failing tests in astropy (e.g. https://github.com/astropy/astropy/pull/5094), a place for discussion for long term solution is in #98

### CODE REVIEW

**Comment by astrofrog** [comment]
Another solution is to add ``defaults`` explicitly - I think we are running into https://github.com/conda/conda/issues/2675

**Comment by larrybradley** [comment]
The `travis-ci` tests are still failing for the `numpy` 1.7 and 1.8 tests because `conda` is installing `astropy` 0.3.0 (!) for those tests.

**Comment by astrofrog** [comment]
Can we pin the version of conda used?

**Comment by bsipocz** [comment]
what you mean @astrofrog? anaconda doesn't build new versions against old numpies, this the old ones are stucked with the astropy version of the time when they were new.
gitter?

**Comment by larrybradley** [comment]
Can `conda` downgrade itself?

The other option would be if old versions of `miniconda` are still available for download and then not run `conda update conda` after installation.

**Comment by astrofrog** [comment]
I'm thinking that the issues we are seeing today are a conda bug, so I'm just wondering whether we can revert to an earlier version of conda.

**Comment by astrofrog** [comment]
By the way, looks like SunPy are having issues too: https://travis-ci.org/sunpy/sunpy/jobs/137763718

**Comment by astrofrog** [comment]
@larrybradley - I think conda can downgrade itself, yes.

**Comment by bsipocz** [comment]
I believe that the conda bug was solved with adding the ``defaults`` to the channels. The issue now is coming from the fact that we removed ``astropy-ci-extras``.

This is the list of the available astropy versions on conda:
```
(astropy-dev)bsipocz@tegla2:~/munka/devel/ci-helpers$ ~/miniconda/bin/conda search astropy|grep np18
Could not connect to https://conda.binstar.org/astrofrog/osx-64/
Could not connect to https://conda.binstar.org/astropy/osx-64/
                             0.3.0                np18py33_0  defaults        
                             0.3.0                np18py27_0  defaults        
                             0.3.0                np18py26_0  defaults        
                             0.3.1                np18py33_0  defaults        
                             0.3.1                np18py27_0  defaults        
                             0.3.1                np18py26_0  defaults        
                             0.3.2                np18py34_0  defaults        
                             0.3.2                np18py33_0  defaults        
                             0.3.2                np18py27_0  defaults        
                             0.3.2                np18py26_0  defaults        
                             0.4rc1               np18py34_0  defaults        
                             0.4rc1               np18py33_0  defaults        
                             0.4rc1               np18py27_0  defaults        
                             0.4rc1               np18py26_0  defaults        
                             0.4                  np18py34_0  defaults        
                             0.4                  np18py33_0  defaults        
                             0.4                  np18py27_0  defaults        
                             0.4                  np18py26_0  defaults        
                             0.4.1                np18py34_0  defaults        
                             0.4.1                np18py33_0  defaults        
                             0.4.1                np18py27_0  defaults        
                             0.4.1                np18py26_0  defaults   
```

**Comment by astrofrog** [comment]
Ok - I think we should add back astropy-ci-helpers for now and we might be back to normal? Then we can try and phase it out more gradually?

**Comment by bsipocz** [comment]
Yes, that's a sensible workaround.

**Comment by astrofrog** [comment]
By the way, I wonder if as ci-helpers gets adopted by more projects, we need either a twitter account or a simple status page so that if people are running into issues, they can see if we are working on it?

**Comment by bsipocz** [comment]
Maybe. Though I would go to the issue tracker first when trying to figure out such info rather than to twitter.

**Pull request merged**
