### PR TITLE
Activate conda on Windows the official™️ way

### PR DESCRIPTION
**Pull request by mwcraig**
Builds are failing on appveyor very early in the setup process. The issue is https://github.com/conda/conda/issues/8836, though the most useful bits are at https://github.com/conda/conda/issues/8836#issuecomment-508815777 and the changes are based on https://github.com/geopandas/geopandas/pull/1029/files

I don't have a windows machine handy, so we'll see what appveyor thinks about this...

### CODE REVIEW

**Comment by mwcraig** [comment]
Sample appveyor failure in astropy that this is trying to solve: https://ci.appveyor.com/project/Astropy/astropy/builds/26358052#L80

**Comment by mwcraig** [comment]
"Progress": a new error:

[`Could not find conda environment: test`](https://ci.appveyor.com/project/Astropy/ci-helpers/builds/26360077/job/onn00cnaal5riwr5#L994)

At least conda didn't crash!

**Comment by astrofrog** [comment]
Are you ok? 😅

**Comment by mwcraig** [comment]
> Are you ok? 😅

I am now that we are planning to switch to travis 😀🎊

If there are packages that need an immediate fix, this *might* work, not sure whether it should be merged.

I think it is time to reconsider how far back in time supported setups go. Switching travis resolves the powershell/`conda init` in appveyor issues but not the "environment is unsolvable" issues.

**Comment by bsipocz** [comment]
hmm, appveyor seems to be failing here 🤷‍♀

**Comment by mwcraig** [comment]
yeah, the only "progress" is that the problem now is conda's failure to find a dependency solution for python 3.5/numpy 1.13/other stuff: https://ci.appveyor.com/project/Astropy/ci-helpers/builds/26360800/job/62bmesl534ck6laf#L222 and later in the log.

The original problem was that conda immediately failed because setting the path is no longer enough to properly activate conda.

I'm planning to solve my immediate problem (ccdproc windows testing) I'm going to switch to travis for windows.

**Comment by djhoese** [comment]
@mwcraig Do you plan on working any more on this now that you've switched to travis for Windows on your own stuff?

**Comment by bsipocz** [comment]
@djhoese - Matt might want to finish this off, but we've switched over quite a few packages now, and I suppose there won't be much more support in the future for the appveyor configs from the astropy side (I'll add a note to the readme about it).

**Comment by bsipocz** [comment]
(frankly the appveyor side with PS and etc  was always a pain to maintain and we could never keep up with the options available for travis).

**Comment by mwcraig** [comment]
@djhoese -- I'm not going to be able to keep this moving forward, unfortunately, though I can try to help if you want to give it a shot.

The easiest path forward, I think, is to drop the fancy `retry_on_known_error` on appveyor in powershell (too impenetrable to debug, it only looks for conda http errors anyway) and cut back the range of supported numpy/python combinations on python.

I've just tried to kick off the test cases that never ran on appveyor because of the failure on python 3.5 to how much would need to be dropped.

**Comment by mwcraig** [comment]
@bsipocz -- is there a way to make appveyor do all of the builds instead of cancelling the rest after one fails?

**Comment by bsipocz** [comment]
sure, remove `   fast_finish: true` from L72. 
We didn't do that as it sucks up so much appveyor time to run the full matrix with the one parallel build, but now it's less of an issue as the org is moving away from that queue.

**Comment by djhoese** [comment]
I don't *need* to be using appveyor. I have also had trouble with appveyor in the past. The only reason I ever got Windows CI to work was because of ci-helpers so either we (I'm willing to help) fix ci-helpers to work with it or we all switch to travis for Windows CI. I just enabled windows on travis for one of my projects, if it passes I'll probably drop appveyor.

**Comment by mwcraig** [comment]
OK; I may try one more commit that will fix most of the current appveyor failures. I'll probably cut myself off after that. 

Travis windows is pretty slow to install things but is blissfully simply to set up.

I've heard azuer is very fast and setting up conda is trivial, but haven't explored it much.

**Comment by djhoese** [comment]
Travis Windows seems to hang for me using ci-helpers: https://travis-ci.org/pytroll/pyresample/jobs/566738141

**Comment by mwcraig** [comment]
I would try restarting the build. I’ve seen this, no idea what causes it, but a restart helps

**Comment by djhoese** [comment]
I had restarted yesterday, just did it again, and still hanging. I took my travis yaml and added:

```
  - env: PYTHON_VERSION=3.7
    os: windows
    language: bash
```

And nothing else. I can make a separate issue for this if you can help me. Otherwise if I need to re-RTFM I can do that too.

**Comment by mwcraig** [comment]
@djhoese -- my changes in ccdproc to use windows on travis are here: https://github.com/astropy/ccdproc/pull/691/files#diff-354f30a63fb0907d4ad57269548329e3

**Comment by djhoese** [comment]
The only difference I see is your default language being "c". I tried that and still seems to get stuck after conda installation. I'm installing packages from conda-forge and installing different packages but I don't see how that would be a problem. Will have to keep guessing.

**Comment by mwcraig** [comment]
I'm not sure what is breaking...grasping at straws, here are a couple ideas:

try `MINICONDA_VERSION=latest`? And maybe `CONDA_VERSION=4.7`?

**Comment by djhoese** [comment]
Looks like miniconda_version doesn't accept `latest`. I removed the MINICONDA_VERSION and now all jobs are failing: https://travis-ci.org/pytroll/pyresample/builds/567052068

**Comment by bsipocz** [comment]
@djhoese - I run into hanging builds, then realized the windows travis has a very limited number of languages it supports.

**Comment by bsipocz** [comment]
Hmm, weird that the `latest` is not accepted, we have that for appveyor 🤷‍♀

**Comment by mwcraig** [comment]
> Looks like miniconda_version doesn't accept latest. I removed the MINICONDA_VERSION and now all jobs are failing: https://travis-ci.org/pytroll/pyresample/builds/567052068

Ouch, sorry about that...I don't see what is going wrong in the logs. I broke all of the tests for ci-helpers in #405, so I think I understand this less well than I thought....

**Comment by bsipocz** [comment]
Well, I should look at code before commenting. @djhoese - it seems that our windows setup is way much simpler than the linux, thus it can't handle `latest`. If you have time, a PR would be welcome.

**Comment by mwcraig** [comment]
If you want to try it with that latest to see if it works, use `MINICONDA_VERSION=4.7.10`, which is the current latest.

**Comment by mwcraig** [comment]
No clue whether that will ork....

**Comment by djhoese** [comment]
I set `MINICONDA_VERSION=4.7.10` and the log says that that version doesn't exist even though I see it here: https://repo.anaconda.com/miniconda/

Log here: https://travis-ci.org/pytroll/pyresample/jobs/567102303

**Comment by bsipocz** [comment]
Yes, I believe the windows setup script needs to be changed to be more like the others.

I've added the issue to my weekend list, but of course would be super happy if someone else would pick it up :)

**Comment by mwcraig** [comment]
4.7.10 is failing because helpers installs conda from chocolatey instead of anaconda. Experimenting with changing that in #405...

**Comment by djhoese** [comment]
I just noticed that before you commented. I removed the forced miniconda version, set 'strict' channel priority, and now I'm just getting hanging jobs for every travis environment: https://travis-ci.org/pytroll/pyresample/builds/567195979

Going to step away from this for a day or two or I'm going to end up reading all of the ci-helpers source code. Thanks for your help so far, let me know if you need me to try anything else.

**Comment by djhoese** [comment]
Correct me if I'm wrong, but this PR needs to be updated to use `strict`, `flexible`, and `disabled` for conda channel priority, right? I can try taking this PR over in a separate PR.

**Comment by mwcraig** [comment]
That is correct; feel free to use anything from here that you find to be useful! The old `true` is now `flexible` and the old `false` is `disabled`.

**Comment by mwcraig** [comment]
Closing, because #416 works

**Pull request closed without merging**
