### PR TITLE
Removing channels added by default

### LINKED ISSUE #119: Remove default channels (astropy, openastronomy, astropy-ci-extras)
At the moment four channels are used unless the user sets ``CONDA_CHANNELS``. These are ``defaults``, ``astropy-ci-extras``, ``astropy``, and ``openastronomy``.

Recently we saw a few problems when a package is available in both ``astropy`` and ``openastronomy`` and still somehow the build ends in conflicts, e.g. https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/147998479#L526

So I propose to remove openastronomy from the default channels (as we tend to host all of dependencies of the affiliates in astropy). Should any package needs something from that channel they can specify it in  ``CONDA_CHANNELS``.

Thoughs @astrofrog, @mwcraig?

### PR DESCRIPTION
**Pull request by bsipocz**
This is to close #119.
Should not be merged before the related PRs merged to the affiliates.

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - I've opened the related PRs to all the affiliates/related packages that use any of the packages we host on any of those channels. So I guess if all of these are merged, this PR is ready to go.

**Comment by astrofrog** [comment]
Looks good to me (if tests pass)

**Comment by bsipocz** [comment]
Should we send out an e-mail to astropy-dev when this is merged? I think I've checked all affiliated packages (and a few others, too), but there may be some more experimental ones out there that could run into troubles after this PR.

**Comment by astrofrog** [comment]
@bsipocz - yes, that sounds reasonable. I actually wonder how many packages *really* need astropy-ci-extras (I'll try some like WCSAxes without any channels)

**Comment by bsipocz** [comment]
Packages that test againts lts astropy will need it I think.

**Comment by bsipocz** [comment]
All the package PRs are merged, so I'm merging this now. 

Watch out @astrofrog, we can expect a few related failures from random packages out there.

**Pull request merged**
