### PR TITLE
Update numpy version to latest stable version

### PR DESCRIPTION
**Pull request by mwcraig**
Continuum builds of numpy 1.11 have been released.

### CODE REVIEW

**Comment by mwcraig** [comment]
Actually, maybe hold off on merging this. Astropy has not been built for numpy 1.11 yet.

**Comment by bsipocz** [comment]
it looks like there is no 1.11 windows build for py3.5 yet? at least the appveyor build doesnt work yet: https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.374/job/e7rvunilk9qy3arq#L146

**Comment by mwcraig** [comment]
Apparently no numpy 1.11 for win/py35 yet. The astropy version it is picking up in that appveyor job is numpy 1.10.

**Comment by bsipocz** [comment]
Ohh, yes you're right, I misread the astropy version.

I suggest to wait with this for a couple of days and then I retry the appveyor build. I don't think much development is planned here in the meantime so it won't matter if the local tests fail atm. 
Once all green, this will be merged.

**Comment by mwcraig** [comment]
Based on the [comment here](https://github.com/conda-forge/conda-smithy/pull/111#issuecomment-204792965) it may be a while until astropy is available for numpy 1.11.

**Comment by bsipocz** [comment]
Thanks again @mwcraig.

**Pull request merged**
