### PR TITLE
Added miniconda 2 or 3 option

### PR DESCRIPTION
**Pull request by dpshelio**
This is to avoid donwloading py2 stuff and then upgrade

### CODE REVIEW

**Comment by dpshelio** [comment]
Builds in sunpy (eg. sunpy/sunpy#1862 - [failed job](https://travis-ci.org/sunpy/sunpy/jobs/148661088)) are failing and this seems a solution that worked if using [my fork](https://travis-ci.org/dpshelio/sunpy/jobs/148677580)

**Comment by bsipocz** [comment]
Sure, we can have this, but I wonder whether getting rid of the extra download overhead is actually worth the added complexity. 
This only make things better for the py3.5 tests as for py 2.6  this is gets the python3 version, and the old way would have been a plug and play even if continuum changes the default to python3, and for python 3.3 and 3.4 one still needs those version.

**Comment by bsipocz** [comment]
@dpshelio - Your fails seems to be those one of those ``conda-forge`` issues @mwcraig was complaining about. E.g. you should not install python from conda-forge but from defaults.

**Comment by bsipocz** [comment]
cc@astrofrog - Do you have an idea why are so many python2.7 packages picked up from ``conda-forge`` in this py3.5 build? Can we do something about it, looks very messy?
https://travis-ci.org/sunpy/sunpy/jobs/148661088#L510

**Comment by dpshelio** [comment]
Yep, it was not the downloading overhead what it brought me to this patch, but the fact of anaconda installing packages of different versions of python and failing.  As you correctly said this could be a problem with `conda-forge` which it goes out of my understanding at the moment.

Regarding 2.7 condition, we could compare it numerically, using `-le` for `<=` instead of `==` so 2.6 would install `miniconda2` too.

**Comment by bsipocz** [comment]
@dpshelio - Could you please restart that failing sunpy build? It worked on my fork as is, so may have been a temporary thing.

**Comment by bsipocz** [comment]
🎉

**Comment by bsipocz** [comment]
@dpshelio - As your problem was just fluke, do you mind if we close this?

**Pull request closed without merging**
