### PR TITLE
Don't use quiet mode when DEBUG is True

### PR DESCRIPTION
**Pull request by astrofrog**
This mirrors on AppVeyor was is done on Travis

@bsipocz - I took this opportunity to also fix https://github.com/astropy/ci-helpers/issues/87, because it turns out the DEBUG=True build had an error which wasn't causing AppVeyor to fail.

### CODE REVIEW

**Comment by astrofrog** [comment]
This should not be merged yet, doing some tests

**Comment by astrofrog** [comment]
@bsipocz - this is ready for review

**Comment by astrofrog** [comment]
Oops I remembered you are on holiday :) I'll go ahead and merge this since it seems to be working well (I'll revert if any issues come up)

**Comment by bsipocz** [comment]
Thanks @astrofrog!

**Pull request merged**
