### PR TITLE
Added tests for --parallel and --open-files

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - Could you add a test for ``--parallel`` to ``test_env.py``? Otherwise this looks good and should be merged.

**Comment by astrofrog** [comment]
@bsipocz - the ``py.test -n 4`` will fail if ``pytest-xdist`` is not installed, so we're already testing it in a way. I'll try and see if we can test this further in ``test_env.py``.

**Comment by bsipocz** [comment]
OK, indeed. In that case this is already good to go.

**Comment by bsipocz** [comment]
@astrofrog - Could you rebase this? It's not exactly clear what triggered the "out-of-date with the base master" claim, maybe it always comes up once a PR is merged and ``ci-helpers`` requires a pass from travis and appveyor for merges?

**Comment by astrofrog** [comment]
@bsipocz - done, sorry it took so long!

**Comment by bsipocz** [comment]
This failed on appveyor as 1.1 got released in the meantime, but the version numbers were not updated here. I've fixed it in #31, but most probably this will need to be rebased again as the merge status got grey (and I dont think restarting the test on appveyor will change that).

**Comment by bsipocz** [comment]
@astrofrog - Just as I though. Appveyor passes when restarted, but still cannot merge it only after a rebase. Could you please rebase it again?

**Comment by astrofrog** [comment]
@bsipocz - done :)

**Comment by bsipocz** [comment]
Thanks @astrofrog.

**Pull request merged**
