### PR TITLE
Use built-in Miniconda on AppVeyor

### PR DESCRIPTION
**Pull request by astrofrog**
I often see this error on AppVeyor:

https://ci.appveyor.com/project/astrofrog/glue-3d-viewer/build/1.0.265

Not sure what causes this flakiness, but it turns out Miniconda is already installed on AppVeyor, so this PR is just an experiment to see if we can just use that.

### CODE REVIEW

**Comment by bsipocz** [comment]
If this would get rid of those random fails it would be awesome. (It was quite annoying when I asap wanted to get the mkl fix out and one of the many builds always failed.)

**Comment by astrofrog** [comment]
@bsipocz - there's a failure but I think it might be a real failure with the latest Numpy version. Have you seen it before?

**Comment by bsipocz** [comment]
@astrofrog - No I haven't. But there is a strange thing with having different sizes for mkl that I don't understand. Versions are the same, both python and mkl wise. For any case I restarted the builds, hoping that it was just a random error.

https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.394/job/jtx9wvyjr17ddvxm#L85

vs the last successful build:

https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.392/job/uem58laaly7ikpgs#L96

**Comment by bsipocz** [comment]
Sadly it's consistent. 

My only wild guess is that the path is not right, the buildin miniconda installs packages somewhere but doesn't update the path, thus pip doesn't see them installed.

**Comment by astrofrog** [comment]
@bsipocz - I'll dig into this later today.

**Comment by astrofrog** [comment]
I'm going to close this - no time to work on it and after thinking about this some more I think it's good we keep complete control over the conda installation.

**Comment by bsipocz** [comment]
Today I had to compile a patched numpy for a conda env and run into the very same problem you had here with the missing mkl. The solution is to add a ``site.cfg`` file, including the path for the lib and include dirs.

Do you think that this PR would get rid of the random build fails? If yes I could give it a try based it on top of this branch.

**Pull request closed without merging**
