### PR TITLE
Making sure all conda pendenency package is written lowercase

### PR DESCRIPTION
**Pull request by bsipocz**
in the pinfile, too. This should have been part of #45.

### CODE REVIEW

**Comment by bsipocz** [comment]
@hamogu - could you restart your failing travis build? This PR should have fixed it.

**Comment by hamogu** [comment]
It works! Thanks!

**Comment by embray** [comment]
This seems to have caused various builds for Astropy to break :/

**Comment by bsipocz** [comment]
@embray - Yes, pinning the version numbers in #43 caused more bugs in corner cases than it solved. The fix is coming in #48, just need to wait for appveyor and travis.

**Comment by hamogu** [comment]
Do we need a ci-helpers-test package, that is cloned when astropy-test-package (to be written) and astropy-affiliated-test-package (to be written) are build?
And then ci-helpers would be a clone of the last commit of ci-helpers-test that passed with a astropy-test-pacakge and astropy-affiliated-test-package ...

Arg, my head hurts from thinking about so many levels of nested testing the tests...

**Comment by bsipocz** [comment]
Or we just need to be even more careful with the tests here, to make sure they cover all the extra cases (e.g conda does some tricks with package names and version numbers when it's in the command line, but it requires the pin file to be more pedantic (e.g conda packages are always lowercase, still it passes with mixed cases, or extends invalid version numbers, e.g it silently treats numpy=1.10 as numpy=1.10*, etc.). Some of these caught in the original PR, but sadly some slipped through. 
I even though that gawk may be a problem and should use awk instead, but didn't make it a test case.

**Pull request merged**
