### PR TITLE
Update pinned conda version to 4.5.10

### PR DESCRIPTION
**Pull request by astrofrog**
This is just to see if all the tests pass with the latest version - and since it's bugfix release number 10, I'm hoping it has some degree of stability...

### CODE REVIEW

**Comment by bsipocz** [comment]
Previously we tested these conda updates with some of the packages as well to avoid unpleasant surprises (astropy/photutils are the usual suspects, but it can be any non super trivial package really). 
Also, I recall to ask @drdavella to check whether that given version works well with some of his most problematic packages, but couln't find any trace of those conversations with a very quick look now.

**Comment by astrofrog** [comment]
@bsipocz - you might be thinking of the conversation in #273? I've copied over one of your commits from there that appears to be needed. Once we get the CI passing here, I agree we need to test it out with a few packages.

**Comment by bsipocz** [comment]
@astrofrog - Yes, that's the one, thanks for digging it up.

**Comment by drdavella** [comment]
This needs to go through ASAP since we're now seeing the following test failure in various repos:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda==4.3.34
  - conda[version='>=4.5.11']
```

I'm not sure what's causing the error on one of the travis jobs above, though.

**Comment by astrofrog** [comment]
@drdavella - there are a couple of real failures here. Do you have any time to investigate? If so, feel free to push commits to my branch!

**Comment by cdeil** [comment]
In Gammapy I think all builds travis-ci builds started to fail today with the conda UnsatisfiableError that @drdavella mentioned above. See https://travis-ci.org/gammapy/gammapy/builds/424488564

**Comment by eteq** [comment]
I was trying this separately in #313 (as @drdavella points out this is urgent, so hopefully this closes #312 ), but there has since been another point update, so I pushed up 4.5.11 to see if that works...

**Comment by eteq** [comment]
As much as it pains me to suggest this, I wonder if it's best to merge this (since we know it at least helps *some* of the packages, which are all failing now) and try to sort out the failing test ASAP after?

**Comment by astrofrog** [comment]
AppVeyor was passing before, it's just not smart enough to recognize the same commit. Ready to merge!

**Comment by astrofrog** [comment]
@cdeil - can you try again to make sure this fixes things?

**Comment by cdeil** [comment]
Seems to run OK again for Gammapy.

See https://github.com/gammapy/gammapy/pull/1762 or https://travis-ci.org/gammapy/gammapy/builds/424543992

Thank you all for the hotfix and for maintaining the ci-helpers!

**Pull request merged**
